# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: epic_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65pic_image.proto\"\x07\n\x05\x65mpty\"\x15\n\x06status\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\'\n\x0fwatchsourceinfo\x12\x14\n\x0csrcinfo_json\x18\x01 \x01(\t\"\x1c\n\twatchlist\x12\x0f\n\x07pd_json\x18\x01 \x01(\t\"0\n\nepic_image\x12\x0e\n\x06header\x18\x01 \x01(\t\x12\x12\n\nimage_cube\x18\x02 \x01(\x0c\x32\xbd\x01\n\x11\x65pic_post_process\x12&\n\x0f\x66ilter_and_save\x12\x0b.epic_image\x1a\x06.empty\x12.\n\x15\x66ilter_and_save_chunk\x12\x0b.epic_image\x1a\x06.empty(\x01\x12%\n\x0f\x66\x65tch_watchlist\x12\x06.empty\x1a\n.watchlist\x12)\n\x0cwatch_source\x12\x10.watchsourceinfo\x1a\x07.statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'epic_image_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_STATUS']._serialized_start=29
  _globals['_STATUS']._serialized_end=50
  _globals['_WATCHSOURCEINFO']._serialized_start=52
  _globals['_WATCHSOURCEINFO']._serialized_end=91
  _globals['_WATCHLIST']._serialized_start=93
  _globals['_WATCHLIST']._serialized_end=121
  _globals['_EPIC_IMAGE']._serialized_start=123
  _globals['_EPIC_IMAGE']._serialized_end=171
  _globals['_EPIC_POST_PROCESS']._serialized_start=174
  _globals['_EPIC_POST_PROCESS']._serialized_end=363
# @@protoc_insertion_point(module_scope)
